### ISSUE TITLE
background添加的图片好像是不支持旋转的，只能拖动。而且拖动的反应很慢。

### ISSUE THREAD

**Issue by zhdxcz** [xd-tayde/touchkit#10]
这个我将想要旋转的背景图片使用add方法添加，因为要解决第一个添加的贴纸为背景而且不能覆盖后加的贴纸，所以我强制将第一个添加的此背景图的z-index设置成50。并且在输出图片前，强制将touchkit._zIndexBox.zIndexArr数组里的'mt-child-0'(第一个加入的贴纸），放在数组最前面。就可以，正常输出合成后的图片了。

**Comment by xd-tayde** [comment]
了解这个需求，我想想怎么从内部做支持。感谢哈。
