### ISSUE TITLE
请问可以插入一段文字吗？

### ISSUE THREAD

**Issue by senson2018** [xd-tayde/touchkit#3]
想要加一段文字，但是复制粘贴使用
obj.text('hello world',{
    width:'300px',
    align:'center',
    pos:{
        x:0,
        y:0,
    },
})
的时候报错了    obj.text is undefined  !!

**Comment by xd-tayde** [comment]
你写的这个是mcanvas的API哈。。touchkit这边并没有这个功能哈。

**Comment by senson2018** [comment]
呜呜呜 ，，，香菇哦。。。我刚刚想了一个方法，不知道可行不可行。。我把mcanvas.js也加载进来。使用他的文字生成的base64的。。可是，，遇到点麻烦，，我新创建了一个demo，加载了mcanvas.js，没有写div，，，直接照文档写了new MCanvas()   ，改了下图片路劲，，，然后，，，浏览器报错在了mcanvas.js:283:5 这个位置。。。。蓝瘦蓝瘦~~~~~~

**Comment by senson2018** [comment]
呜呜呜。。。
