### ISSUE TITLE
亲，我可以使用按钮控制图片旋转吗？

### ISSUE THREAD

**Issue by senson2018** [xd-tayde/touchkit#7]
场景是这样的，我把图片缩放到合适之后，再把图片移动到合适的位置，此时发现，旋转有点偏差，但是手动调整对于某些机型存在一定难度，我打算加个按钮在界面，然后点击这个按钮，图片可以旋转回角度为0的，请问这个可以实现吗？？？？

**Comment by xd-tayde** [comment]
现在好像是没有开发这样的API呢。~不过你可以直接从外部操作对应的贴纸的dom节点，将rotate参数都置为0。应该能做到

**Comment by senson2018** [comment]
好哦。。。我试试哈！！！

**Comment by senson2018** [comment]
@xd-tayde 好哦。。我试试哈
