### ISSUE TITLE
你好，在PC端不能移动图片元素，但是按F12变成移动端就可以移动元素了，为什么呢？有什么办法在PC端也可以移动和缩放

### ISSUE THREAD

**Issue by purestart** [xd-tayde/touchkit#8]
你好，在PC端不能移动图片元素，但是按F12变成移动端就可以移动元素了，为什么呢？有什么办法在PC端也可以移动和缩放

**Comment by xd-tayde** [comment]
现在确实是不支持PC端的。~因为里面用到的事件是touchstart/move/end。暂时没有适配。sorry！

**Comment by purestart** [comment]
我看事件基于mTouch  最新版mTouch可以在pc端使用，可以更新下吗？持续关注中。。。
   mTouch 兼容写法 ，将事件类型按是否支持touch 判断是touchxxx还是mousexxx
    //事件类型列表
    var eventList = {
        TOUCH_START: util.hasTouch ? 'touchstart' : 'mousedown',
        TOUCH_MOVE: util.hasTouch ? 'touchmove' : 'mousemove',
        TOUCH_END: util.hasTouch ? 'touchend' : 'mouseup',
    ...}

**Comment by xd-tayde** [comment]
是可以简单这样处理。但是可能会存在未知的问题。所以还是需要一个成本。可能再后续的版本中进行兼容。
