### ISSUE TITLE
touchkit.bakcground在Ios下不支持长度较长的base64

### ISSUE THREAD

**Issue by zhdxcz** [xd-tayde/touchkit#9]
hello,在使用过程中发现个问题哈。使用touchkit.bakcground的时候,image属性设置为较长的base64码的时候，会在ios手机上渲染不出来。具体表现就是在ios上上传大图片后，将image设置成对应的base64会无法渲染。在安卓下没问题。而且当把image换成url链接时就都支持了

**Comment by xd-tayde** [comment]
这可能跟IOS的限制有关，这个可能需要再研究下。

**Comment by zhdxcz** [comment]
辛苦大佬啊~
